# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.8'

gem 'puma', '~> 5.6'
gem 'rack-contrib', '~> 2.3'
gem 'rack-cors'
gem 'sinatra', '~> 2.2'
gem 'sinatra-contrib'

gem 'manabi', git: 'https://github.com/Catsuko/manabi.git', branch: 'main', glob: 'core/*.gemspec'

group :development, :test do
  gem 'byebug'
  gem 'rubocop'
  gem 'rubocop-rspec'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
